Review of fixed source bank model developments
davidjohnlong/openmc pull request #2
Opened 2020-03-09 11:32 UTC by davidjohnlong

2020-03-09 22:33 UTC, simondrichards commented on include/openmc/particle.h
> +	    double wgt;
The OpenMC Style Guide for C++ says to use two spaces per indentation level. The other struct definitions in this file have conformed to this guide, so it's probably best if this one does too.

2020-03-09 22:53 UTC, simondrichards commented on src/simulation.cpp
> +	}
Use two spaces per indentation level.

2020-03-09 23:06 UTC, simondrichards commented on src/simulation.cpp
>    }
Use two spaces per indent. I couldn't find mention in the OpenMC Style Guide for C++ about the indent for continuation lines, but elsewhere in the code it looks like the continuation line is aligned with the first character after the opening parenthesis on the preceding line.

```suggestion
  if (settings::run_mode == RunMode::FIXED_SOURCE &&
      !settings::path_source_library.empty()) {
    load_custom_source_library();
  }
```

2020-03-10 09:26 UTC, davidjohnlong commented
The suggested changes have been made. Assigned review back to @simondrichards to accept.

2020-03-10 11:37 UTC, simondrichards requested changes
Sorry for the piecemeal review - I started this last night by adding individual comments, when I should have done it all as part of a proper review. A few more examples of wrong indentation, some of which are caused by TAB characters. It's probably better to avoid using TABs altogether and just use spaces.

Apart from the minor formatting issues it all looks good to me. It still passes the regression tests and no longer writes the source bank to the statepoint file, which is all good.

I noticed that the runtime section of the statepoint file still contains an entry for "sampling source sites" which now has the value zero. In some ways this makes sense as we no longer spend time filling the source bank. But the time for sampling source sites isn't zero in reality - it's just that it is now folded into the transport time, presumably. I'm not sure how we want to handle this - do we just leave this entry there with a value of zero, or remove this field entirely? It's probably not going to be practical or sensible to measure the times for sampling individual particles at transport time and summing them, is it? Maybe the best thing is to raise this question on the pull-request?

Once the minor formatting changes are committed I think this is ready to merge to your develop branch and submit a pull-request to openmc-dev/develop.

Thanks.

2020-03-10 11:37 UTC, simondrichards commented on src/state_point.cpp
```suggestion
    if (settings::path_sourcepoint == settings::path_statepoint &&
        !source_present) {
      fatal_error("Source bank must be contained in statepoint restart file");
    }
  }

```

2020-03-10 11:37 UTC, simondrichards commented on include/openmc/particle.h
> +  };
TAB character messing up indentation. Replace with spaces.

```suggestion
  struct RestartBank {
    Position r;
    Direction u;
    double E;
    double wgt;
  };
```

2020-03-10 11:37 UTC, simondrichards commented on include/openmc/particle.h
> +  };
TAB character messing up indentation. Replace with spaces.

```suggestion
  struct RestartBank {
    Position r;
    Direction u;
    double E;
    double wgt;
  };
```

2020-03-10 11:37 UTC, simondrichards commented on src/simulation.cpp
> +    }
```suggestion
    if (settings::run_mode == RunMode::EIGENVALUE) {
      initialize_source();
    }
```

2020-03-10 11:37 UTC, simondrichards commented on src/simulation.cpp
> +  }
```suggestion
  if (settings::run_mode == RunMode::FIXED_SOURCE &&
      !settings::path_source_library.empty()) {
    close_custom_source_library();
  }
```

2020-03-10 11:37 UTC, simondrichards commented on src/simulation.cpp
> +  }
More TABs messing up indentation: 

```suggestion
  if(settings::run_mode == RunMode::FIXED_SOURCE) {
    // initialize random number seed
    int64_t id = (simulation::total_gen + overall_generation() - 1)*settings::n_particles +
      simulation::work_index[mpi::rank] + index_source;
    uint64_t seed = init_seed(id, STREAM_SOURCE);
    // sample from external source distribution or custom library then set
    Particle::Bank site;
    if (!settings::path_source_library.empty()) {
      site = sample_custom_source_library(&seed);
    } else {
      site = sample_external_source(&seed);
    }
    p->from_source(&site);
  } else if (settings::run_mode == RunMode::EIGENVALUE) {
    // set defaults for eigenvalue simulations from primary bank
    p->from_source(&simulation::source_bank[index_source - 1]);
  }
```

2020-03-10 12:11 UTC, davidjohnlong commented
Further corrections to the formatting have been added. 

Agreed that the sampling time for the fixed source case is now "folded" into the transport time and it probably does not make sense to take individual timings of these and sum them over all samples, however this is a choice for the OpenMC community and as you state should be raised in the pull request.

2020-03-10 12:15 UTC, davidjohnlong commented on src/simulation.cpp
> +  }
Done

2020-03-10 12:15 UTC, davidjohnlong commented on src/simulation.cpp
> +  }
Done

2020-03-10 12:16 UTC, davidjohnlong commented on src/simulation.cpp
> +    }
Done

2020-03-10 12:22 UTC, merged

2020-03-10 12:22 UTC, simondrichards commented
Thanks @davidjohnlong - looks good.